name: promptprobe-ci
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python harness/run_suite.py --adapter echo --out ./reports
      - uses: actions/upload-artifact@v4
        with: { name: promptprobe-reports, path: reports/* }
